<?php

/**
 * UserForm class.
 * UserForm is the data structure for keeping
 * user form data. It is used by the 'user' action of 'SiteController'.
 */
class InvoiceForm extends CFormModel
{
	/* User Fields */
	public $id;
	public $invoice_no;////账单编号
	public $invoice_dt;//账单日期
	public $payment_term;//付款方式
	public $customer_code;//客户编号
	public $invoice_to_name;//发票公司
    public $invoice_to_addr;//发票地址
    public $invoice_to_tel;//服务电话
    public $sales_id;//销售
    public $sales_name;//销售
    public $staff_id;//销售
    public $staff_name;//销售
    public $addr;//联系人地址
    public $tel;//联系人电话
    public $name_zh;//联系人
    public $old_no;//U系统编号
    public $invoice_amt;//合计
    public $type=array();//详细记录
    public $generated_by;//生成账单人员
    public $remarks;//特别说明

    public $bowl;//
    public $baf;//
    public $hand;//
    public $urinal;//
    public $hsd;//
    public $td;//
    public $sink;//
    public $abhsd;//
    public $ptd;//
    public $ttl;//
    public $aerosal;//
    public $toiletRoom;//

    public $city;//
    public $description;
    public $quantity;
    public $product_name;
    public $qty;
    public $unit_price;
    public $amount;
    public $disc;

    private $infoStyle="font-weight: bold;font-size: 14px;";

	/**
	 * Declares customized attribute labels.
	 * If not declared here, an attribute would have a label that is
	 * the same as its name with the first letter in upper case.
	 */
	public function attributeLabels()
	{
		return array(
            'id'=>Yii::t('invoice','Record ID'),
            'invoice_no'=>Yii::t('invoice','Number'),
            'invoice_dt'=>Yii::t('invoice','Date'),
            'customer_code'=>Yii::t('invoice','Customer Account'),
            'invoice_to_name'=>Yii::t('invoice','Invoice Company'),
            'payment_term'=>Yii::t('invoice','Payment Term'),
			'invoice_to_addr'=>Yii::t('invoice','Invoice Address'),
            'invoice_to_tel'=>Yii::t('invoice','Invoice Tel'),
            'sales_name'=>Yii::t('invoice','Salesperson'),
            'staff_name'=>Yii::t('invoice','technician'),
            'name_zh'=>Yii::t('invoice','Delivery Company'),
            'addr'=>Yii::t('invoice','Delivery Address'),
            'tel'=>Yii::t('invoice','Delivery Tel'),
            'old_no'=>Yii::t('invoice','old number no.'),
            'remarks'=>Yii::t('invoice','remarks'),

            'invoice_amt'=>Yii::t('invoice','Total Amount'),
            'city'=>Yii::t('invoice','City'),
            'generated_by'=>Yii::t('invoice','Generated By'),

            'bowl'=>Yii::t('invoice','bowl'),
            'baf'=>Yii::t('invoice','baf'),
            'hand'=>Yii::t('invoice','hand'),
            'urinal'=>Yii::t('invoice','urinal'),
            'hsd'=>Yii::t('invoice','hsd'),
            'td'=>Yii::t('invoice','td'),
            'sink'=>Yii::t('invoice','sink'),
            'abhsd'=>Yii::t('invoice','abhsd'),
            'ptd'=>Yii::t('invoice','ptd'),
            'ttl'=>Yii::t('invoice','ttl'),
            'aerosal'=>Yii::t('invoice','aerosal'),
            'toiletRoom'=>Yii::t('invoice','toiletRoom'),
		);
	}

	/**
	 * Declares the validation rules.
	 */
	public function rules()
	{
		return array(
			array('id,type,generated_by,old_no,name_zh,tel,addr,sales_name,staff_name
			,bowl,baf,hand,urinal,hsd,td,sink,abhsd,ptd,ttl,aerosal,toiletRoom
			,payment_term,remarks,invoice_to_tel,invoice_to_addr,invoice_to_name,invoice_amt
			,invoice_no,invoice_dt,customer_code','safe'),
			array('','required'),
			//array('bowl,baf,hand,urinal,hsd,td,sink,abhsd,ptd,ttl,aerosal,toiletRoom','number'),
			array('type','validateType'),
//			array('code','safe','on'=>'edit'),

		);
	}
    public function validateType($attribute, $params) {
	    if(!empty($this->type)){
	        $invoice_amt = 0;
	        foreach ($this->type as $key=>$row){
	            if(!key_exists("product_name",$row)||!key_exists("qty",$row)||!key_exists("unit_price",$row)){
                    $this->addError($attribute, "关键字段不存在，请刷新重试");
                    return false;
                }
                if(!is_numeric($row["qty"])||!is_numeric($row["unit_price"])){
                    $this->addError($attribute, "数量及单价只能为数字");
                    return false;
                }
                $amount = floatval($row["qty"])*floatval($row["unit_price"]);
                $this->type[$key]["amount"] = $amount;
                $invoice_amt+=$amount;
            }
            $this->invoice_amt = $invoice_amt;
        }
    }

	public function retrieveData($index)
	{
        $suffix = Yii::app()->params['envSuffix'];
		$city = Yii::app()->user->city_allow();
		$sql = "select * from acc_invoice where id=$index and city in ($city)";
		$rows = Yii::app()->db->createCommand($sql)->queryAll();
		if (count($rows) > 0)
		{
			foreach ($rows as $row)
			{
			    $sql1="select * from acc_invoice_type where invoice_id='".$row['id']."'";
                $type = Yii::app()->db->createCommand($sql1)->queryAll();
//                $sql2="select * from swoper$suffix.swo_company where code='".$row['customer_account']."'";
//                $delivery = Yii::app()->db->createCommand($sql2)->queryRow();
                $this->type = $type;
                $this->id = $row['id'];
				$this->customer_code = $row['customer_code'];
                $this->invoice_dt = General::toDate($row['invoice_dt']);
				$this->payment_term = $row['payment_term'];

				$this->invoice_amt = $row['invoice_amt'];
				$this->invoice_no = $row['invoice_no'];
				$this->invoice_to_name = $row['invoice_to_name'];
				$this->invoice_to_addr = $row['invoice_to_addr'];
				$this->invoice_to_tel = $row['invoice_to_tel'];
				$this->remarks = $row['remarks'];
				$this->sales_name = $row['sales_name'];
				$this->staff_name = $row['staff_name'];
				$this->staff_id = current(explode(" ",$this->staff_name));
				$this->addr = $row['addr'];
				$this->tel = $row['tel'];
				$this->name_zh = $row['name_zh'];
				$this->old_no = $row['old_no'];
				//$this->total_amount = round($total_amount,2);//sprintf("%.2f",$total_amount)

                $this->bowl = empty($row['bowl'])?0:$row['bowl'];
                $this->baf = empty($row['baf'])?0:$row['baf'];
                $this->hand = empty($row['hand'])?0:$row['hand'];
                $this->urinal = empty($row['urinal'])?0:$row['urinal'];
                $this->hsd = empty($row['hsd'])?0:$row['hsd'];
                $this->td = empty($row['td'])?0:$row['td'];
                $this->sink = empty($row['sink'])?0:$row['sink'];
                $this->abhsd = empty($row['abhsd'])?0:$row['abhsd'];
                $this->ptd = empty($row['ptd'])?0:$row['ptd'];
                $this->ttl = empty($row['ttl'])?0:$row['ttl'];
                $this->aerosal = empty($row['aerosal'])?0:$row['aerosal'];
                $this->toiletRoom = empty($row['toiletRoom'])?0:$row['toiletRoom'];

                $this->city = $row['city'];
				$this->generated_by = $this->getNames($row['lcu']);
				break;
			}
		}
		return true;
	}

	public function newData($date){
        $this->city = Yii::app()->user->city();
//        $this->city='SG';
        $start=$date['start'];
        $end=$date['end'];
        $model=new Invoice;
        /*模擬數據-start*/
        //$this->city="NN";
        //$start="2021-06-01";
        //$end="2021-06-05";
        /*模擬數據-end*/
        $arr=$model->getData($this->city,$start,$end);
//        print_r('<pre>');
        //print_r($arr);
        //die();
        if(key_exists("message",$arr)&&$arr["message"]=="Success"&&isset($arr['data'])){
            $connection = Yii::app()->db;
            $transaction=$connection->beginTransaction();
            try {
                $this->saveU($connection,$arr);
                $transaction->commit();
            }
            catch(Exception $e) {
                $transaction->rollback();
                throw new CHttpException(404,'Cannot update.'.$e->getMessage());
            }
        }

    }

    /**
     * @param $connection
     * @param $arr
     */
    public function saveU(&$connection, $arr){
        if(!empty($arr['data'])){
            foreach ($arr['data'] as $a){
                $invoice_no = key_exists("invoice_no",$a)?$a["invoice_no"]:"";
                $invoice_no = end(explode($this->city,$invoice_no));
//	        $sql_s="select id from acc_invoice where dates='".$invoice_dt."' and customer_account='".$a['customer_code']."' and invoice_no='".$a['invoice_no']."'";
                $sql_s="select id from acc_invoice where invoice_no='".$invoice_no."' and customer_code='".$a['customer_code']."' and city='$this->city'";
                $records = Yii::app()->db->createCommand($sql_s)->queryRow();
                if(!$records){
//        $sql="insert into acc_invoice (dates,payment_term,customer_po_no,customer_account,salesperson,sales_order_no,sales_order_date,ship_via,invoice_company,invoice_address,invoice_tel,delivery_company,delivery_address,delivery_tel,description,quantity,unit_price,disc,amount,sub_total,gst,total_amount,generated_by,lcu,luu) value ()";
                    $uid = Yii::app()->user->id;
                    Yii::app()->db->createCommand()->insert("acc_invoice",array(
                        'customer_code'=>key_exists("customer_code",$a)?$a["customer_code"]:"",
                        'invoice_dt'=>key_exists("invoice_dt",$a)?$a["invoice_dt"]:null,
                        'dates'=>key_exists("invoice_dt",$a)?$a["invoice_dt"]:null,
                        'invoice_no'=>key_exists("invoice_no",$a)?$a["invoice_no"]:"",
                        'invoice_to_name'=>key_exists("invoice_to_name",$a)?$a["invoice_to_name"]:"",
                        'invoice_to_addr'=>key_exists("invoice_to_addr",$a)?$a["invoice_to_addr"]:"",
                        'invoice_to_tel'=>key_exists("invoice_to_tel",$a)?$a["invoice_to_tel"]:"",
                        'payment_term'=>key_exists("payment_term",$a)?$a["payment_term"]:"",
                        'sales_id'=>key_exists("sales_id",$a)?$a["sales_id"]:"",
                        'sales_name'=>key_exists("sales_name",$a)?$a["sales_name"]:"",
                        'staff_id'=>key_exists("staff_id",$a)?$a["staff_id"]:"",
                        'staff_name'=>key_exists("staff_name",$a)?$a["staff_name"]:"",
                        'addr'=>key_exists("addr",$a)?$a["addr"]:"",
                        'tel'=>key_exists("tel",$a)?$a["tel"]:"",
                        'name_zh'=>key_exists("name_zh",$a)?$a["name_zh"]:"",
                        'city'=>$this->city,
                        'lcu'=>$uid
                    ));
                    $id = Yii::app()->db->getLastInsertID();
                    if(!empty($id)){
                        $arr = array();
                        //invoice_amt,remarks,is_service
                        $strList = array("","2","3","4","5","6");//詳情物品需要循環的列表
                        $number = 0;//统计发票有几个有效物品
                        $invoice_amt = 0;//发票的总金额
                        $old_no = key_exists("invoice_no",$a)?array($a["invoice_no"]):array();//发票编号多个编号用,分割
                        $remarks="";//發票的特別說明
                        foreach ($a["line"] as $line){
                            if(key_exists("staff_id",$line)){
                                $arr['staff_id'] = $line["staff_id"];
                            }
                            if(key_exists("sales_name",$line)){
                                $arr['sales_name'] = $line["sales_name"];
                            }
                            $arr['bowl'] = key_exists("bowl",$line)?$line["bowl"]:null;
                            $arr['baf'] = key_exists("baf",$line)?$line["baf"]:null;
                            $arr['hand'] = key_exists("hand",$line)?$line["hand"]:null;
                            $arr['urinal'] = key_exists("urinal",$line)?$line["urinal"]:null;
                            $arr['hsd'] = key_exists("hsd",$line)?$line["hsd"]:null;
                            $arr['td'] = key_exists("td",$line)?$line["td"]:null;
                            $arr['sink'] = key_exists("sink",$line)?$line["sink"]:null;
                            $arr['abhsd'] = key_exists("abhsd",$line)?$line["abhsd"]:null;
                            $arr['ptd'] = key_exists("ptd",$line)?$line["ptd"]:null;
                            $arr['ttl'] = key_exists("ttl",$line)?$line["ttl"]:null;
                            $arr['aerosal'] = key_exists("aerosal",$line)?$line["aerosal"]:null;
                            $arr['toiletRoom'] = key_exists("toiletRoom",$line)?$line["toiletRoom"]:null;
                            $remarks = key_exists("remarks",$line)?$line["remarks"]:"";
                            $line["invoice_no"] = key_exists("invoice_no",$line)?$line["invoice_no"]:"";
                            if($line["invoice_no"]!=""&&!in_array($line["invoice_no"],$old_no)){
                                $old_no[] = $line["invoice_no"];
                            }
                            foreach ($strList as $key=>$strExpr){//開始循環添加發票的詳情物品
                                if(key_exists("unit_price$strExpr",$line)&&$line["unit_price$strExpr"]!=0){
                                    $number++;
                                    $line["unit_price$strExpr"] = key_exists("unit_price$strExpr",$line)?$line["unit_price$strExpr"]:0;
                                    $line["qty$strExpr"] = key_exists("qty$strExpr",$line)?$line["qty$strExpr"]:0;
                                    if($key==0&&key_exists("is_service",$line)&&$line['is_service']=='Y'){
                                        $amount=key_exists("invoice_amt",$line)?$line['invoice_amt']:0;
                                    }else{
                                        $amount=$line["unit_price$strExpr"]*$line["qty$strExpr"];
                                    }
                                    $invoice_amt+=$amount;
                                    Yii::app()->db->createCommand()->insert("acc_invoice_type",array(
                                        'invoice_id'=>$id,
                                        'product_code'=>key_exists("product_code$strExpr",$line)?$line["product_code$strExpr"]:"",
                                        'product_name'=>key_exists("product_name$strExpr",$line)?$line["product_name$strExpr"]:"",
                                        'unit'=>key_exists("unit$strExpr",$line)?$line["unit$strExpr"]:"",
                                        'qty'=>$line["qty$strExpr"],
                                        'unit_price'=>$line["unit_price$strExpr"],
                                        'package'=>key_exists("package$strExpr",$line)?$line["package$strExpr"]:"",
                                        'amount'=>$amount,
                                        'is_service'=>key_exists("is_service",$line)?$line["is_service"]:null,
                                        'lcu'=>$uid
                                    ));
                                }
                            }
                        }
                        $updateArr=array(
                            'invoice_no'=>$invoice_no,
                            'old_no'=>implode(",",$old_no),
                            'invoice_amt'=>$invoice_amt,
                            'luu'=>null,
                            'page_num'=>$number,
                            'remarks'=>$remarks,
                        );
                        $updateArr = array_merge($arr,$updateArr);
                        Yii::app()->db->createCommand()->update("acc_invoice",$updateArr,"id=:id",array(":id"=>$id));//修改發票的總金額及特別說明
                    }
                }
            }
        }
    }
	
	public function saveData()
	{

		$connection = Yii::app()->db;
		$transaction=$connection->beginTransaction();
		try {
			$this->saveInvoice($connection);
			$transaction->commit();
		}
		catch(Exception $e) {
			$transaction->rollback();
			throw new CHttpException(404,'Cannot update.'.$e->getMessage());
		}
	}

	protected function saveInvoice(&$connection)
	{
		$sql = '';
		switch ($this->scenario) {
			case 'delete':
				$sql = "delete from acc_invoice where id = :id and city = :city";
				break;
			case 'edit':
				$sql = "update acc_invoice set
                            payment_term=:payment_term,                                                                                                             
                            name_zh=:name_zh,                                                                                                              
                            addr=:addr,                                                                                                              
                            tel=:tel,                                                                                                              
                            remarks=:remarks,                                                                                                              
                            staff_name=:staff_name,                                                                                                              
                            invoice_amt=:invoice_amt,                                                                                                              
                            bowl=:bowl,                                                                                                              
                            baf=:baf,                                                                                                              
                            hand=:hand,                                                                                                              
                            urinal=:urinal,                                                                                                              
                            hsd=:hsd,                                                                                                              
                            td=:td,                                                                                                              
                            sink=:sink,                                                                                                              
                            abhsd=:abhsd,                                                                                                              
                            ptd=:ptd,                                                                                                              
                            ttl=:ttl,                                                                                                              
                            aerosal=:aerosal,                                                                                                              
                            toiletRoom=:toiletRoom,                                                                                                              
                            luu=:luu
						where id = :id and city = :city
						";
				break;
		}

		$city = Yii::app()->user->city();
		$uid = Yii::app()->user->id;
		$command=$connection->createCommand($sql);
		if (strpos($sql,':payment_term')!==false)
			$command->bindParam(':payment_term',$this->payment_term,PDO::PARAM_STR);
		if (strpos($sql,':invoice_to_name')!==false)
            $command->bindParam(':invoice_to_name',$this->invoice_to_name,PDO::PARAM_STR);
        if (strpos($sql,':invoice_to_addr')!==false)
            $command->bindParam(':invoice_to_addr',$this->invoice_to_addr,PDO::PARAM_STR);
        if (strpos($sql,':invoice_to_tel')!==false)
            $command->bindParam(':invoice_to_tel',$this->invoice_to_tel,PDO::PARAM_STR);
        if (strpos($sql,':staff_name')!==false)
            $command->bindParam(':staff_name',$this->staff_name,PDO::PARAM_STR);
        if (strpos($sql,':name_zh')!==false)
            $command->bindParam(':name_zh',$this->name_zh,PDO::PARAM_STR);
        if (strpos($sql,':addr')!==false)
            $command->bindParam(':addr',$this->addr,PDO::PARAM_STR);
        if (strpos($sql,':tel')!==false)
            $command->bindParam(':tel',$this->tel,PDO::PARAM_STR);
        if (strpos($sql,':remarks')!==false)
            $command->bindParam(':remarks',$this->remarks,PDO::PARAM_STR);
        if (strpos($sql,':invoice_amt')!==false)
            $command->bindParam(':invoice_amt',$this->invoice_amt,PDO::PARAM_INT);

        if (strpos($sql,':bowl')!==false)
            $command->bindParam(':bowl',$this->bowl,PDO::PARAM_STR);
        if (strpos($sql,':baf')!==false)
            $command->bindParam(':baf',$this->baf,PDO::PARAM_STR);
        if (strpos($sql,':hand')!==false)
            $command->bindParam(':hand',$this->hand,PDO::PARAM_STR);
        if (strpos($sql,':urinal')!==false)
            $command->bindParam(':urinal',$this->urinal,PDO::PARAM_STR);
        if (strpos($sql,':hsd')!==false)
            $command->bindParam(':hsd',$this->hsd,PDO::PARAM_STR);
        if (strpos($sql,':td')!==false)
            $command->bindParam(':td',$this->td,PDO::PARAM_STR);
        if (strpos($sql,':sink')!==false)
            $command->bindParam(':sink',$this->sink,PDO::PARAM_STR);
        if (strpos($sql,':abhsd')!==false)
            $command->bindParam(':abhsd',$this->abhsd,PDO::PARAM_STR);
        if (strpos($sql,':ptd')!==false)
            $command->bindParam(':ptd',$this->ptd,PDO::PARAM_STR);
        if (strpos($sql,':ttl')!==false)
            $command->bindParam(':ttl',$this->ttl,PDO::PARAM_STR);
        if (strpos($sql,':aerosal')!==false)
            $command->bindParam(':aerosal',$this->aerosal,PDO::PARAM_STR);
        if (strpos($sql,':toiletRoom')!==false)
            $command->bindParam(':toiletRoom',$this->toiletRoom,PDO::PARAM_STR);

		if (strpos($sql,':luu')!==false)
			$command->bindParam(':luu',$uid,PDO::PARAM_STR);
        if (strpos($sql,':city')!==false)
            $command->bindParam(':city',$city,PDO::PARAM_STR);
        if (strpos($sql,':id')!==false)
            $command->bindParam(':id',$this->id,PDO::PARAM_INT);
		$command->execute();
		foreach ($this['type'] as $arr){
            switch ($this->scenario) {
                case 'delete':
                    $sql1 = "delete from acc_invoice_type where id = :id ";
                    break;
                case 'edit':
                    $sql1 = "update acc_invoice_type set
                            product_name=:product_name,
                            qty=:qty,
                            unit_price=:unit_price,
                            amount=:amount                  
						where id = :id 
						";
                    break;
            }
            $command=$connection->createCommand($sql1);
            if (strpos($sql1,':product_name')!==false)
                $command->bindParam(':product_name',$arr['product_name'],PDO::PARAM_STR);
            if (strpos($sql1,':qty')!==false)
                $command->bindParam(':qty',$arr['qty'],PDO::PARAM_STR);
            if (strpos($sql1,':unit_price')!==false)
                $command->bindParam(':unit_price',$arr['unit_price'],PDO::PARAM_STR);
            if (strpos($sql1,':amount')!==false)
                $command->bindParam(':amount',$arr['amount'],PDO::PARAM_STR);
            if (strpos($sql1,':id')!==false)
                $command->bindParam(':id',$arr['id'],PDO::PARAM_INT);
            $command->execute();
            //print_r('<pre>');print_r($this);exit();
        }

		return true;
	}


    public function isReadOnly() {
//		return ($this->scenario=='view'||$this->status=='V'||$this->posted||!empty($this->req_ref_no)||!empty($this->t3_doc_no));
        return ($this->scenario!='new');
    }

    public function getNames($id)
    {
        $suffix = Yii::app()->params['envSuffix'];
        $sql = "select name from hr$suffix.hr_employee where id=(SELECT employee_id from hr$suffix.hr_binding WHERE user_id='".$id."')";
        $row = Yii::app()->db->createCommand($sql)->queryScalar();
        return  $row;
    }

    public function deleteData($a){
        $sql = "delete from acc_invoice where id = '$a'";
        Yii::app()->db->createCommand($sql)->execute();
        $sql1 = "delete from acc_invoice_type where invoice_id = '$a'";
        Yii::app()->db->createCommand($sql1)->execute();
    }

    //獲取pdf模板內容（包含發票單號、日期、技術員、總價）
    private function getPDFTable($model){
        $info_style=$this->infoStyle;
        $html = "";
//812px *572
        //LBS信息
        $html.='
<table border="0" width="812px" cellspacing="0" cellpadding="0" style="line-height: 13px;">
	<tr>
		<td width="180px"> </td>
		<td width="148px" rowspan="6" style="text-align: left;"><img width="111px"  src="images/lbs_pdf.jpg" ></td>
		<td width="119px" rowspan="6" style="text-align: center;">
		    <span style="color:red;font-size: 18px;">發票</span>
		    <br>
		    <span style="color: black;font-weight: bold;font-size: 18px;">INVOICE</span>
		</td>
		<td width="180px" style="font-weight: bold;font-size: 11px;">寄往</td>
		<td width="215px" style="font-weight: bold;font-size: 10.5px;">REMIT TO:</td>
	</tr>
	<tr>
		<td rowspan="5">
		    <span style="color:red;font-weight: bold;font-size: 9px">發票編號</span><br>
		    <span style="font-weight: bold;font-size: 9px;">INVOICNE NO.</span><br>
		    <span style="'.$info_style.'">  '.$model->invoice_no.'</span>
		</td>
		<td><span>史偉莎澳門(由佳駿企業有限公司經營)</span></td>
		<td><span >LBS Macau (O/B Kai Jun Enterprises Ltd.)</span></td>
	</tr>
	<tr>
		<td><span>澳門慕拉士大馬路一八五至一九一號</span></td>
		<td><span>Avenida Venceslau de Morais NO185 - 191,</span></td>
	</tr>
	<tr>
		<td><span>澳門工業中心十樓B座</span></td>
		<td><span>10 Andar B Ed Centro Industrial Macau, Macau</span></td>
	</tr>
	<tr>
		<td><span>電話：(853) 2871 9588 傳真：2871 9727</span></td>
		<td><span>Tel.: (853) 2871 9588 Fax: 2871 9727</span></td>
	</tr>
	<tr>
		<td><span style="color:red;">(支票抬頭 “佳駿企業有限公司”)</span></td>
		<td><span style="color:red;">(Cheque payable to“Kai Jun Enterprises Ltd.”)</span></td>
	</tr>
</table>
';

        //客戶信息
        $html.='
<table border="0" width="812px" cellspacing="0" cellpadding="0" style="line-height: 9.5px;">
	<tr><td colspan="5" style="border-bottom: 2px solid black; line-height: 3px;" height="3px;"></td></tr>
	<tr><td colspan="5" style="line-height: 5px;" height="5px;"></td></tr>
	<tr style="background-color: #e6e6e6;">
	    <td width="5px"></td>
		<td width="395px;">
			<span style="color: red;">顧客號碼</span><br/>
			<span>CUSTOMER NUMBER</span>
		</td>
		<td width="15px" style="background-color: #fff;"> </td>
	    <td width="5px"></td>
		<td width="125px;">
			<span style="color: red;">坐廁</span><br/>
			<span>Bowls</span>
		</td>
		<td width="140px;">
			<span style="color: red;">電動清新機</span><br/>
			<span>BAF</span>
		</td>
		<td width="130px;" colspan="2">
			<span style="color: red;">手部消毒機</span><br/>
			<span>Hand Sanitizer</span>
		</td>
	</tr>
	<tr>
	    <td> </td>
		<td>
			<span style="color: red;">顧客名稱</span><br/>
			<span>CUSTOMER NAME</span>
		</td>
		<td style="background-color: #fff;"> </td>
	    <td> </td>
		<td>
			<span style="color: red;">尿缸</span><br/>
			<span>Urinals</span>
		</td>
		<td>
			<span style="color: red;">皂液機</span><br/>
			<span>HSD</span>
		</td>
		<td colspan="2">
			<span style="color: red;">廁紙機</span><br/>
			<span>TD</span>
		</td>
	</tr>
	<tr style="background-color: #e6e6e6">
	    <td> </td>
		<td>
			<span style="color: red;">地址</span><br/>
			<span>ADDRESS</span>
		</td>
		<td style="background-color: #fff;"> </td>
	    <td> </td>
		<td>
			<span style="color: red;">洗手盤</span><br/>
			<span>Sinks</span>
		</td>
		<td>
			<span style="color: red;">除菌皂液機</span><br/>
			<span>ABHSD</span>
		</td>
		<td colspan="2">
			<span style="color: red;">抹手紙機</span><br/>
			<span>PTD</span>
		</td>
	</tr>
	<tr>
		<td colspan="2"> </td>
		<td style="background-color: #fff;"> </td>
	    <td> </td>
		<td>
			<span style="color: red;">總數</span><br/>
			<span>Total</span>
		</td>
		<td>
			<span style="color: red;">噴機</span><br/>
			<span>Spary BAF</span>
		</td>
		<td colspan="2">
			<span style="color: red;">洗手間數目</span><br/>
			<span>No. of Room</span>
		</td>
	</tr>
	<tr style="background-color: #e6e6e6">
		<td height="20px;" colspan="2"></td>
		<td style="background-color: #fff;"> </td>
		<td colspan="5"> </td>
	</tr>
	<tr>
	    <td rowspan="2"> </td>
		<td rowspan="2">
			<span style="color: red;">付款方式</span><br/>
			<span>TERMS: DUE UPON RECEIPT</span><br/>
			<span style="color: red;">所有裝置均為史偉莎澳門所擁有，只隨服務提供</span><br/>
			<span style="font-size: 6.5px;">ALL MACHINES ARE FURNISHED FOR SERVICE ONLY AND REMAIN THE PROPERTY OF LBS HYGIENE SERVICES.</span>
		</td>
		<td colspan="6" style="line-height: 2px" height="2px"> </td>
	</tr>
	<tr>
		<td colspan="2"> </td>
		<td colspan="4">
			<span style="color: red;">史偉莎澳門之滅蟲服務員已清楚闡明及警告處理老鼠藥餌之方法並已於有擺放藥餌之位置貼上警告標貼。（只適用於採用滅鼠服務之客戶）</span><br/>
			<span style="font-size: 6.5px;">THIS IS TO ACKNOWLEDGE THAT LBS MACAU PEST CONTROL OFFICER DID EXPLAIN AND PUT WARNING LABELS REGARDING RODENT BAITS AT BAITING LOCATIONS.(ONLY APPLICABLE TO CUSTOMERS WITH RODENT CONTROL SERVICE)</span>
		</td>
	</tr>
	<tr>
	    <td colspan="8" height="2px;" style="line-height: 2px;border-bottom: 2px solid black;"> </td>
    </tr>
	<tr>
	    <td colspan="8" height="4px;" style="line-height: 4px;"> </td>
    </tr>
	<tr>
		<td colspan="2">
		    <span style="width: 4px;"> </span>
			<span style="color: red;">產品名稱</span><br/>
			<span>DESCRIPTION</span>
		</td>
		<td colspan="2"> </td>
		<td>
		    <span style="width: 10px;">  </span>
			<span style="color: red;">數量</span><br/>
			<span>QUANTITY</span>
		</td>
		<td style="text-align: center;">
            <span style="color: red;">單價</span><br/>
			<span>UNIT PRICE</span>
		</td>
		<td width="120px" style="text-align: right;">
		    <span style="color: red;">金額     </span><br/>
			<span>AMOUNT</span>
		</td>
		<td width="10px"> </td>
	</tr>
	<tr>
	    <td colspan="8" height="4px;" style="line-height: 4px;border-bottom: 2px solid black;"> </td>
    </tr>
</table>
';
        //特別說明及付款碼
        $html.='
<table border="0" width="812px" cellspacing="0" cellpadding="0" style="line-height: 9.5px;">
    <tr><td colspan="3" style="line-height: 170px;"></td></tr>
    <tr>
        <td colspan="3"><span style="color:red;">特別提示</span><br/>
            <span>SPECIAL INSTRUCTIONS:</span>
        </td>
    </tr>
    <tr>
        <td width="10px;"></td>
        <td width="90px;"><img width="90px" src="images/pay.jpg"/></td>
        <td> </td>
    </tr>
    <tr>
        <td></td>
        <td style="text-align: center">付款可掃二維碼</td>
        <td> </td>
    </tr>
    <tr><td colspan="3" style="line-height: 10px;" height="10px;"></td></tr>
</table>
        ';
        //发票日期及技術員
        $html.='
<table border="0" width="812px" cellspacing="0" cellpadding="0" style="line-height: 9.5px;">
    <tr>
        <td width="86px" style="color:red;font-weight: bold;">服務技術員名稱</td>
        <td width="105px" rowspan="2" style="border-bottom: 1px solid black;text-align:center;'.$info_style.'">'.$model->staff_id.'</td>
        <td width="5px" rowspan="2"></td>
        <td width="143px" style="color:red;font-weight: bold;">客戶簽署及蓋印</td>
        <td width="105px" rowspan="2" style="border-bottom: 1px solid black;"> </td>
        <td width="5px" rowspan="2"></td>
        <td width="25px" style="color:red;font-weight: bold;">日期</td>
        <td width="120px" rowspan="2" style="border-bottom: 1px solid black;text-align:center;'.$info_style.'">'.$model->invoice_dt.'</td>
        <td width="5px" rowspan="2"></td>
        <td width="65px" style="color:red;font-weight: bold;">總金額</td>
        <td width="140px" rowspan="2" style="border-bottom: 1px solid black;'.$info_style.'">'.$model->invoice_amt.'</td>
    </tr>
    <tr>
        <td style="font-weight: bold;">Name of Technician</td>
        <td style="font-weight: bold;">Customer’s signature & Co.Chop</td>
        <td style="font-weight: bold;">Date</td>
        <td style="font-weight: bold;">Total Amount</td>
    </tr>
</table>
        ';
        return $html;
    }

    //給pdf模板填寫服務(客戶名稱、客戶需要的服務）
    private function insertModelForPDF(&$pdf,$model){
        $info_style=$this->infoStyle;
        $html='<span style="'.$info_style.'">'.$model->customer_code.'</span>';
        //$w, $h, $x, $y, $html='', $border=0
        $pdf->writeHTMLCell(106,8,42,35,$html,0);
        $html='<span style="'.$info_style.'">'.$model->name_zh.'</span>';
        $pdf->writeHTMLCell(120,8,37,42,$html,0);
        $html='<span style="'.$info_style.'">'.$model->addr.'</span>';
        $pdf->writeHTMLCell(123,22,25,49,$html,0);
        $html='<span style="'.$info_style.'">'.$model->payment_term.'</span>';
        $pdf->writeHTMLCell(95,8,50,69,$html,0);
        //坐廁 電動清新機 手部消毒機$w, $h, $x, $y, $html='', $border=0
        $model->bowl=empty($model->bowl)?"":$model->bowl;
        $model->baf=empty($model->baf)?"":$model->baf;
        $model->hand=empty($model->hand)?"":$model->hand;
        $model->urinal=empty($model->urinal)?"":$model->urinal;
        $model->hsd=empty($model->hsd)?"":$model->hsd;
        $model->sink=empty($model->sink)?"":$model->sink;
        $model->td=empty($model->td)?"":$model->td;
        $model->abhsd=empty($model->abhsd)?"":$model->abhsd;
        $model->ptd=empty($model->ptd)?"":$model->ptd;
        $model->ttl=empty($model->ttl)?"":$model->ttl;
        $model->aerosal=empty($model->aerosal)?"":$model->aerosal;
        $model->toiletRoom=empty($model->toiletRoom)?"":$model->toiletRoom;
        $html='<span style="'.$info_style.'">'.$model->bowl.'</span>';
        $pdf->writeHTMLCell(30,8,163,35,$html,0);
        $html='<span style="'.$info_style.'">'.$model->baf.'</span>';
        $pdf->writeHTMLCell(30,8,213,35,$html,0);
        $html='<span style="'.$info_style.'">'.$model->hand.'</span>';
        $pdf->writeHTMLCell(20,8,267,35,$html,0);
        //尿缸 皂液機 廁紙機 $w, $h, $x, $y, $html='', $border=0
        $html='<span style="'.$info_style.'">'.$model->urinal.'</span>';
        $pdf->writeHTMLCell(30,8,163,42,$html,0);
        $html='<span style="'.$info_style.'">'.$model->hsd.'</span>';
        $pdf->writeHTMLCell(30,8,213,42,$html,0);
        $html='<span style="'.$info_style.'">'.$model->td.'</span>';
        $pdf->writeHTMLCell(30,8,267,42,$html,0);
        //洗手盤 除菌皂液機 抹手紙機 $w, $h, $x, $y, $html='', $border=0
        $html='<span style="'.$info_style.'">'.$model->sink.'</span>';
        $pdf->writeHTMLCell(30,8,163,49,$html,0);
        $html='<span style="'.$info_style.'">'.$model->abhsd.'</span>';
        $pdf->writeHTMLCell(30,8,213,49,$html,0);
        $html='<span style="'.$info_style.'">'.$model->ptd.'</span>';
        $pdf->writeHTMLCell(30,8,267,49,$html,0);
        //總數 噴機 洗手間數目 $w, $h, $x, $y, $html='', $border=0
        $html='<span style="'.$info_style.'">'.$model->ttl.'</span>';
        $pdf->writeHTMLCell(30,8,163,55.5,$html,0);
        $html='<span style="'.$info_style.'">'.$model->aerosal.'</span>';
        $pdf->writeHTMLCell(30,8,213,55.5,$html,0);
        $html='<span style="'.$info_style.'">'.$model->toiletRoom.'</span>';
        $pdf->writeHTMLCell(30,8,267,55.5,$html,0);
        if(!empty($model->type)){
            $html='<table border="0" width="812px" cellspacing="0" cellpadding="0" style="line-height: 10px;">';
            foreach ($model->type as $row){
                $html.='<tr style="'.$info_style.'">';
                $html.='<td width="390px">'.$row['product_name'].'</td>';
                $html.='<td width="100px" style="text-align: center">'.$row['qty'].'</td>';
                $html.='<td width="50px"> </td>';
                $html.='<td width="153px" style="text-align: center">'.$row['unit_price'].'</td>';
                $html.='<td width="110px" style="text-align: right">'.$row['amount'].'</td>';
                $html.='</tr>';
            }
            $html.='</table>';
            //$w, $h, $x, $y, $html='', $border=0
            $pdf->writeHTMLCell(290,45,5,95,$html,0);
        }
        $remarks = str_replace("\n","<br/>",$model->remarks);
        $html='<span style="'.$info_style.'">'.$remarks.'</span>';
        //$w, $h, $x, $y, $html='', $border=0
        $pdf->writeHTMLCell(240,22,40,153,$html,0);
    }

    //對pdf進行默認設置
    private function resetPDFConfig(&$pdf,$model){
        if(!empty($model->invoice_to_name)){
            $pdf->SetTitle($model->invoice_to_name);
        }else{
            $pdf->SetTitle("所有發票");
        }
        $pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
        $pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
        $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
        $pdf->SetFont('msyh', '', 8);
        $t_margin= $pdf->getHeaderHeight()+2;
        $r_margin=5;
        $l_margin=5;
        $pdf->SetMargins($l_margin, $t_margin, $r_margin);
        $h_margin=15;
        $pdf->SetHeaderMargin($h_margin);
        $f_margin=2;
        $pdf->SetFooterMargin($f_margin);
        $b_margin=0;
        $pdf->SetAutoPageBreak(TRUE, $b_margin);
        $pdf->SetPrintHeader(false);
        $pdf->SetPrintFooter(false);
    }

    //打印全部
    public function allPrints(){
        $pdf = new MyPDF2('L', 'mm', 'A4', true, 'UTF-8', false);
        $this->resetPDFConfig($pdf,$this);

        foreach ($_POST['InvoiceList']['attr'] as $a){
            $this->retrieveData($a);
            $pdf->AddPage();
            $tbl = $this->getPDFTable($this);
            $pdf->writeHTML($tbl, true, false, false, false, '');
            $this->insertModelForPDF($pdf,$this);
        }
        ob_clean();
        if(count($_POST['InvoiceList']['attr'])==1){
            $address=str_replace('/','-',$this->invoice_no);
            $address.='.pdf';
        }else{
            $address='all_'.date("Y-m-d").'.pdf';
        }
        $outstring =$pdf->Output($address, 'I');
        return $address;
    }

    //下載全部
    public function allDowns($model){
        $pdf = new MyPDF2('L', 'mm', 'A4', true, 'UTF-8', false);
        $this->resetPDFConfig($pdf,$model);
        $pdf->AddPage();
        $tbl = $this->getPDFTable($model);
        $pdf->writeHTML($tbl, true, false, false, false, '');
        $this->insertModelForPDF($pdf,$model);
        ob_clean();
        $date=str_replace('/','-',$model->invoice_dt);
        $name=str_replace('/',' ',$model->name_zh);
        //$name=iconv("utf-8","gb2312//IGNORE",$name);
        $name=mb_convert_encoding($name, "gb2312", "UTF-8");
        $address="/".$date."-".$name.'.pdf';
        $outstring =$pdf->Output(sys_get_temp_dir().$address, 'F');
        return $address;
    }




    public function zip($files){
//        $files = array('image.jpeg','text.txt','music.wav');
        $fileName="zipped_file.zip";
        $zipname = sys_get_temp_dir().'/'.$fileName;
        $zip = new ZipArchive;
        $zip->open($zipname, ZipArchive::CREATE);
        foreach ($files as $file) {
            $result = basename($file);
            $zip->addFile(sys_get_temp_dir().$file,$result);
        }
        $zip->close();
///Then download the zipped file.
        header('Content-Type: application/zip;charset=utf-8;name='.$fileName);
        header('Content-disposition: attachment; filename='.$fileName);
        header('Content-Length: '.filesize($zipname));
        readfile($zipname);
        unlink($zipname);
        foreach ($files as $a){
            unlink($a);
        }
    }
}
