<?php

class RemitAuditForm extends ExpenseAuditForm
{
    protected $table_type=2;
    protected $fileList=array(
        array("field_id"=>"outside","field_type"=>"list","field_name"=>"outside","display"=>"none"),//外部
        array("field_id"=>"payee","field_type"=>"text","field_name"=>"payee","display"=>"none"),//收款单位
        array("field_id"=>"taxpayer_no","field_type"=>"text","field_name"=>"taxpayer no","display"=>"none"),//纳税人识别号
        array("field_id"=>"bank_name","field_type"=>"text","field_name"=>"bank name","display"=>"none"),//开户行名称
        array("field_id"=>"bank_no","field_type"=>"text","field_name"=>"bank no","display"=>"none"),//银行帐号

        array("field_id"=>"urgent","field_type"=>"list","field_name"=>"urgent","display"=>"none"),//加急
        array("field_id"=>"end_pay_date","field_type"=>"text","field_name"=>"end pay date","display"=>"none"),//最晚付款日
        array("field_id"=>"invoice_bool","field_type"=>"list","field_name"=>"invoice bool","display"=>"none"),//发票情况
        array("field_id"=>"invoice_no","field_type"=>"text","field_name"=>"invoice no","display"=>"none"),//发票号码

        array("field_id"=>"prepayment","field_type"=>"list","field_name"=>"prepayment","display"=>"none"),//预付款
        array("field_id"=>"purchase_type","field_type"=>"list","field_name"=>"purchase type","display"=>"none"),//是否采购单
        array("field_id"=>"purchase_code","field_type"=>"list","field_name"=>"purchase code","display"=>"none"),//采购单编号
        array("field_id"=>"payment_condition","field_type"=>"list","field_name"=>"payment condition","display"=>"none"),//付款条件
        array("field_id"=>"payment_company","field_type"=>"list","field_name"=>"payment company","display"=>"none"),//支付公司
    );

    public function rules()
    {
        $list = parent::rules();
        $list[]=array('exp_code','validatePre','on'=>array("audit"));//
        return $list;
    }

    public function validatePre($attribute, $params) {
        $uid = Yii::app()->user->id;
        if(!empty($this->audit_json)){
            foreach ($this->audit_json as $row){
                if($row["audit_tag"]=="财务部"&&$row["audit_user"]==$uid){
                    $this->finance_bool = true;
                    if(!isset($this->tableDetail["prepayment"])||$this->tableDetail["prepayment"]===""||$this->tableDetail["prepayment"]===null){
                        $this->addError($attribute, "请选择预付款");
                    }
                }
            }
        }
    }

    public function retrieveData($index)
    {
        $bool = parent::retrieveData($index); // TODO: Change the autogenerated stub
        if($bool&&!empty($this->audit_json)){
            $uid = Yii::app()->user->id;
            foreach ($this->audit_json as $row){
                if($row["audit_tag"]=="财务部"&&$row["audit_user"]==$uid){
                    $this->finance_bool = true;
                }
            }
        }
        return $bool;
    }

    protected function saveDataForSql(&$connection)
    {
        if($this->finance_bool){//财务部允许修改预付款
            $field_value = key_exists("prepayment",$this->tableDetail)?$this->tableDetail["prepayment"]:null;
            $rs = Yii::app()->db->createCommand()->select("id,field_id")->from("acc_expense_detail")
                ->where("exp_id=:exp_id and field_id=:field_id",array(
                    ':field_id'=>"prepayment",':exp_id'=>$this->id,
                ))->queryRow();
            if($rs){
                $connection->createCommand()->update('acc_expense_detail',array(
                    "field_value"=>$field_value,
                ),"id=:id",array(':id'=>$rs["id"]));
            }else{
                $connection->createCommand()->insert('acc_expense_detail',array(
                    "exp_id"=>$this->id,
                    "field_id"=>"prepayment",
                    "field_value"=>$field_value,
                ));
            }
        }
        return parent::saveDataForSql($connection); // TODO: Change the autogenerated stub
    }
}