<?php
class RptInvoiceList extends CReport {
	public $show_report_title = false;

	protected function fields() {
		return array(
            'invoice_no'=>array('label'=>Yii::t('invoice','Number'),'width'=>20,'align'=>'L'),
            'invoice_dt'=>array('label'=>Yii::t('invoice','Date'),'width'=>15,'align'=>'C'),
            'head_type'=>array('label'=>Yii::t('invoice','head type'),'width'=>25,'align'=>'L'),
            'customer_code'=>array('label'=>Yii::t('invoice','Customer Account'),'width'=>20,'align'=>'L'),
            'name_zh'=>array('label'=>Yii::t('invoice','Delivery Company'),'width'=>30,'align'=>'L'),
            'addr'=>array('label'=>Yii::t('invoice','Delivery Address'),'width'=>40,'align'=>'L'),
            'tel'=>array('label'=>Yii::t('invoice','Delivery Tel'),'width'=>20,'align'=>'L'),
            'sales_name'=>array('label'=>Yii::t('invoice','Salesperson'),'width'=>15,'align'=>'L'),
            'staff_name'=>array('label'=>Yii::t('invoice','technician'),'width'=>15,'align'=>'L'),
            'payment_term'=>array('label'=>Yii::t('invoice','Payment Term'),'width'=>10,'align'=>'L'),
            'bowl'=>array('label'=>Yii::t('invoice','bowl'),'width'=>10,'align'=>'R'),
            'baf'=>array('label'=>Yii::t('invoice','baf'),'width'=>10,'align'=>'R'),
            'hand'=>array('label'=>Yii::t('invoice','hand'),'width'=>10,'align'=>'R'),
            'urinal'=>array('label'=>Yii::t('invoice','urinal'),'width'=>10,'align'=>'R'),
            'hsd'=>array('label'=>Yii::t('invoice','hsd'),'width'=>10,'align'=>'R'),
            'td'=>array('label'=>Yii::t('invoice','td'),'width'=>10,'align'=>'R'),
            'sink'=>array('label'=>Yii::t('invoice','sink'),'width'=>10,'align'=>'R'),
            'abhsd'=>array('label'=>Yii::t('invoice','abhsd'),'width'=>10,'align'=>'R'),
            'ptd'=>array('label'=>Yii::t('invoice','ptd'),'width'=>10,'align'=>'R'),
            'ttl'=>array('label'=>Yii::t('invoice','ttl'),'width'=>10,'align'=>'R'),
            'aerosal'=>array('label'=>Yii::t('invoice','aerosal'),'width'=>10,'align'=>'R'),
            'toiletRoom'=>array('label'=>Yii::t('invoice','toiletRoom'),'width'=>10,'align'=>'R'),
			'product_code'=>array('label'=>Yii::t('invoice','Product Code'),'width'=>15,'align'=>'L'),
			'product_name'=>array('label'=>Yii::t('invoice','Description'),'width'=>20,'align'=>'L'),
			'qty'=>array('label'=>Yii::t('invoice','Quantity'),'width'=>10,'align'=>'R'),
			'unit_price'=>array('label'=>Yii::t('invoice','Unit Price'),'width'=>10,'align'=>'R'),
			'amount'=>array('label'=>Yii::t('invoice','Amount'),'width'=>10,'align'=>'R'),
            'invoice_amt'=>array('label'=>Yii::t('invoice','Total Amount'),'width'=>10,'align'=>'R'),
            'generated_by'=>array('label'=>Yii::t('invoice','Generated By'),'width'=>20,'align'=>'L'),
		);
	}

	public function genReport() {
		$tmp = array();
		$last_no = '';
		foreach ($this->data as $row) {
/*
			if ($last_no==$row['invoice_no']) {
				$row['invoice_no'] = '';
				$row['invoice_dt'] = '';
				$row['customer_code'] = '';
				$row['name_zh'] = '';
				$row['addr'] = '';
				$row['tel'] = '';
				$row['payment_term'] = '';
				$row['bowl'] = '';
				$row['baf'] = '';
				$row['hand'] = '';
				$row['urinal'] = '';
				$row['hsd'] = '';
				$row['td'] = '';
				$row['sink'] = '';
				$row['abhsd'] = '';
				$row['ptd'] = '';
				$row['ttl'] = '';
				$row['aerosal'] = '';
				$row['toiletRoom'] = '';
				$row['invoice_amt'] = '';
				$row['generated_by'] = '';
			} else {
				$last_no = $row['invoice_no'];
			}
*/
			$tmp[] = $row;
		}
		$this->data = $tmp;
		return $this->exportExcel();
	}

	public function resetDataForList($emailList){
		$this->data=array();
		if(!empty($emailList)){
			foreach ($emailList as $list){
                $records = Yii::app()->db->createCommand()
					->select("product_code,product_name,unit,qty,unit_price,amount")
					->from("acc_invoice_type")->where("invoice_id=:id",array(":id"=>$list["id"]))->queryAll();
                if($records){
                    //$list['invoice_dt'] = date('Y/m/d',strtotime($list['invoice_dt']));
                    $list['head_type'] = empty($list['head_type'])?"佳駿企業有限公司":"LBS (Macau) Limited";
                    $list['city_name'] = General::getCityName($list["city"]);
                	foreach ($records as $record){
                        $temp = array(
                            'invoice_no'=>$list['invoice_no'],
                            'invoice_dt'=>$list['invoice_dt'],
                            'customer_code'=>$list['customer_code'],
                            'name_zh'=>$list['name_zh'],
                            'head_type'=>$list['head_type'],
                            'addr'=>$list['addr'],
                            'tel'=>$list['tel'],
                            'sales_name'=>$list['sales_name'],
                            'staff_name'=>$list['staff_name'],
                            'payment_term'=>$list['payment_term'],
                            'bowl'=>$list['bowl'],
                            'baf'=>$list['baf'],
                            'hand'=>$list['hand'],
                            'urinal'=>$list['urinal'],
                            'hsd'=>$list['hsd'],
                            'td'=>$list['td'],
                            'sink'=>$list['sink'],
                            'abhsd'=>$list['abhsd'],
                            'ptd'=>$list['ptd'],
                            'ttl'=>$list['ttl'],
                            'aerosal'=>$list['aerosal'],
                            'toiletRoom'=>$list['toiletRoom'],
                            'product_code'=>$record['product_code'],
                            'product_name'=>$record['product_name'],
                            'qty'=>$record['qty'],
                            'unit_price'=>$record['unit_price'],
                            'amount'=>$record['amount'],
                            'invoice_amt'=>$list['invoice_amt'],
                            'generated_by'=>$list['generated_by'],
                        );
                        $this->data[]=$temp;
					}
				}
			}
		}
	}

	public function getExportExcel(){
        return $this->exportExcel();
	}
}
?>
